- name: Configure and deploy FinanceMe app
  hosts: test
  become: true
  tasks:
    - name: Update apt
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: ['docker.io']
        state: present

    - name: Start Docker
      systemd:
        name: docker
        enabled: true
        state: started

    - name: Pull Docker Image
      shell: docker pull sarafabhinav1997/financeme-app:latest

    - name: Stop existing container if running
      shell: docker stop financeme || true && docker rm -f financeme || true

    - name: Run container
      shell: docker run -d -p 8084:8081 --name financeme sarafabhinav1997/financeme-app:latest
