---
- name: Install Node Exporter
  hosts: all
  become: yes

  tasks:
    - name: Download Node Exporter
      shell: |
        wget https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz
        tar -xvzf node_exporter-1.7.0.linux-amd64.tar.gz
        mv node_exporter-1.7.0.linux-amd64/node_exporter /usr/local/bin/

    - name: Create Node Exporter user
      user:
        name: nodeuser
        shell: /sbin/nologin

    - name: Create Node Exporter service
      copy:
        dest: /etc/systemd/system/node_exporter.service
        content: |
          [Unit]
          Description=Node Exporter
          After=network.target

          [Service]
          User=nodeusr
          ExecStart=/usr/local/bin/node_exporter

          [Install]
          WantedBy=default.target

    - name: Start Node Exporter
      systemd:
        name: node_exporter
        enabled: yes
        state: started
